export const CREATE_TOKEN = "CREATE_TOKEN";
export const GET_USERS_RESPONSE = "GET_USERS_RESPONSE";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const POST_USER_WITH_GOOGLE = "POST_USER_WITH_GOOGLE";
export const GET_BY_DATE = "GET_BY_DATE";
