export const CREATE_TOKEN = "CREATE_TOKEN";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_SLEEP_BY_DATE = "GET_SLEEP_BY_DATE";
export const GET_SLEEP_BY_RANGE = "GET_SLEEP_BY_RANGE";
